variables:
  ANSIBLE_INVENTORY: "tests/inventory"
  PYTHONUNBUFFERED: "1"
  ANSIBLE_FORCE_COLOR: "true"

.ansible_test_template: &ansible_test
  script:
    - ansible --version
    - ansible-galaxy install -v -r requirements.yml
    - ansible-playbook tests/test.yml --syntax-check
    - ansible-playbook -vvv --connection=local tests/test.yml
    - idempotence=$(mktemp)
    - ansible-playbook -vvv --connection=local tests/test.yml | tee ${idempotence}
    - >
      tail ${idempotence}
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)
# This part is used to check role run.
# Add your own tests depending on your $ROLE
    - echo "=======> Starting output tests"

# We build using (ansiblecheck)[https://hub.docker.com/r/ansiblecheck/ansiblecheck/]
# images It provide a wide variety of OS container images to test with.
# most frequent ones included here

# debian-wheezy:
#   image: ansiblecheck/ansiblecheck:debian-wheezy
#   <<: *ansible_test

debian-jessie:
  image: ansiblecheck/ansiblecheck:debian-jessie
  <<: *ansible_test

debian-stretch:
  image: ansiblecheck/ansiblecheck:debian-stretch
  <<: *ansible_test

debian-buster:
  image: ansiblecheck/ansiblecheck:debian-buster
  <<: *ansible_test

ubuntu-xenial:
  image: ansiblecheck/ansiblecheck:ubuntu-xenial
  <<: *ansible_test

ubuntu-bionic:
  image: ansiblecheck/ansiblecheck:ubuntu-bionic
  <<: *ansible_test

# el-6:
#   image: ansiblecheck/ansiblecheck:el-6
#   <<: *ansible_test

el-7:
  image: ansiblecheck/ansiblecheck:el-7
  <<: *ansible_test

# fedora-23:
#   image: ansiblecheck/ansiblecheck:fedora-23
#   <<: *ansible_test
#
# fedora-24:
#   image: ansiblecheck/ansiblecheck:fedora-24
#   <<: *ansible_test

# archlinux-latest:
#   image: ansiblecheck/ansiblecheck:archlinux-latest
#   <<: *ansible_test
