---
- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Prepare {{ beats__shipper }} config file
  template:
    src: "{{ beats__shipper }}-config.yml.j2"
    dest: /etc/{{ beats__shipper }}/{{ beats__shipper }}.yml
    backup: true
  notify:
    - restart beat

- name: Copy {{ beats__shipper }} modules
  template:
    src: "{{ beats__modules_sourcedir }}/{{ item }}"
    dest: /etc/{{ beats__shipper }}/modules.d/{{ item | basename | regex_replace('\.j2','') }}
    backup: true
  with_items:
    - "{{ beats__modules }}"
  when: beats__modules is defined
  notify:
    - restart beat

- name: Enable {{ beats__shipper }} service
  service:
    name: "{{ beats__package_map[ beats__shipper ] }}"
    enabled: yes

- name: Start {{ beats__shipper }} service
  service:
    name: "{{ beats__package_map[ beats__shipper ] }}"
    state: started
  changed_when: False
  when: beats__autostart
